## Second Assignment

#### 1) Create a function called **"even_squared"** that receives an integer value **N**, and returns a list containing, in ascending order, the square of each of the even values, from 1 to N, including N if applicable. 

In [17]:
def even_squared():
    N = int(input("Number please: "))
    square = []
    for num in range(1,N+1):
        if num % 2 == 0:
            square.append(num**2)
    print("The square of all even values from 1 to " + str(N) + " is " + str(sorted(square)))
        
even_squared()

Number please: 96
The square of all even values from 1 to 96 is [4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216]


#### 2) Using a while loop and the **input()** function, read an indefinite amount of **integers** until the number read is **-1**. After this process, print two lists on the screen: The first containing the even integers, and the second containing the odd integers. Both must be in ascending order. 

In [82]:
even = []
odd = []

num = int(input())

while num != -1:
    if num % 2 == 0:
        even.append(num)
    elif num % 2 != 0:
        odd.append(num)
    num = int(input())
if num == -1:
    print("Even numbers: " + str(sorted(even)) + "\nOdd numbers: " + str(sorted(odd)))
else: print("oops")

3
4
5
8
-2
-1
Even numbers: [-2, 4, 8]
Odd numbers: [3, 5]


#### 3) Create a function called **"even_account"** that receives a list of integers, counts the number of existing even elements, and returns this count. 

In [39]:
def even_account(list):
    even = 0
    for element in list:
        if element % 2 == 0:
            even += 1
    print("There are " + str(even) + " even numbers in the list.")

even_account([1,34,6,17,28,19,20]) 

There are 4 even numbers in the list.


#### 4) Create a function called **"squared_list"** that receives a list of integers and returns another list whose elements are the squares of the elements of the first. 

In [85]:
def squared_list(list):
    squares = []
    for num in list:
        if num % list[0] == 0:
            squares.append(num)
    print("The numbers " + str(squares) + " of the given list are squares of the first given number " + str(list[0]) + ".")

squared_list([3,24,12,55,21,38,33,52])

The numbers [3, 24, 12, 21, 33] of the given list are squares of the first given number 3.


#### 5) Create a function called **"descending"** that receives two lists of integers and returns a single list, which contains all the elements in descending order, and may include repeated elements. 

In [12]:
def descending(list1, list2):
    return sorted(list1 + list2, reverse = True)

descending([1,4,77,23], [40,887,5,2,76])

[887, 77, 76, 40, 23, 5, 4, 2, 1]

#### 6) Create a function called **"adding"** that receives a list **A**, and an arbitrary number of integers as input. Return a new list containing the elements of **A** plus the integers passed as input, in the order in which they were given. Here is an example: 

>```python
>>>> A = [10,20,30]
>>>> adding(A, 4, 10, 50, 1)
> [10, 20, 30, 4, 10, 50, 1]
```

In [29]:
def adding(A,*args):
    for arg in args:
        A.append(arg)
    return A

adding([10,20,30],4,10,50,1)

[10, 20, 30, 4, 10, 50, 1]

#### 7) Create a function called **"intersection"** that receives two input lists and returns another list with the values that belong to the two lists simultaneously (intersection) without repetition of values and in ascending order. Use only lists (do not use sets); loops and conditionals. See the example: 

>```python
>>>> A = [-2, 0, 1, 2, 3]
>>>> B = [-1, 2, 3, 6, 8]
>>>> intersection(A,B)
> [2, 3]
```

In [38]:
def intersection(A,B):
    int = []
    for elem in A:
        if elem == elem in B:
            if elem not in int:
                int.append(elem)
    return sorted(int)

intersection([3,2,3,1,50,5],[1,50,3,4])

[1, 3, 50]

#### 8) Create a function called **"union"** that receives two input lists and returns another list with the union of the elements of the two received, without repetition of elements and in ascending order. Use only lists (do not use sets); loops and conditionals. See the example: 

>```python
>>>> A = [-2, 0, 1, 2]
>>>> B = [-1, 1, 2, 10]
>>>> union(A,B)
> [-2, ,-1, 0, 1, 2, 10]
```

In [48]:
def union(A,B):
    return sorted(dict.fromkeys(A+B))

union([-2,0,1,3,2],[-1,1,2,3,10])

[-2, -1, 0, 1, 2, 3, 10]

#### 9) Generalize the **"intersection"** function so that it receives an indefinite number of lists and returns the intersection of all of them. Call the new function **intersection2**. 

In [86]:
def intersection2(*lists):
    import itertools
    int = list(itertools.chain(*lists)) 
    return sorted(dict.fromkeys(int))

intersection2([3,2,3,1,50,5],[1,50,3,4],[3,5,30,5,18])

[1, 2, 3, 4, 5, 18, 30, 50]

## Challenge

#### 10) Create a function named **"matrix"** that implements matrix multiplication:
    
Given the matrices:
    
$A_{m\times n}=
\left[\begin{matrix}
a_{11}&a_{12}&...&a_{1n}\\
a_{21}&a_{22}&...&a_{2n}\\
\vdots &\vdots &&\vdots\\
a_{m1}&a_{m2}&...&a_{mn}\\
\end{matrix}\right]$
    
We will represent then as a list of lists.

$A = [[a_{11},a_{12},...,a_{1n}],[a_{21},a_{22},...,a_{2n}], . . . ,[a_{m1},a_{m2},...,a_{mn}]]$

The **"matrix"** funtion must receive two matrices $A$ e $B$ in the specified format and return $A\times B$

In [87]:
def matrix():
    import numpy as np
    A = np.array(input("Matrice A: "))
    B = np.array(input("Matrice B: "))
    C = np.matmul(A,B)
    print(C)
    
matrix()

Matrice A: [[1,2,3],[2,3,4],[4,5,6]]
Matrice B: [[2,3,4],[3,4,5],[5,6,7]]
[[23 29 35]
 [33 42 51]
 [53 68 83]]
